### ISSUE TITLE
Add test for stake

### ISSUE THREAD

**Issue by dmytropodelnik** [The-Poolz/Integrate#19]
Add test to prove working Stake() method from FlexStaking repo correctly.

**Comment by YouStillAlive** [comment]
Transaction works on test-bscscan
Steps to reproduce:

1) Approved 10000*(10^18) tokens to flex-staking contract 
https://testnet.bscscan.com/tx/0xd15679437c0d57bd86727cfe1bbec80bc678820e8a06a33fcc84be6b1ed59c44
2) Created new staking pool
https://testnet.bscscan.com/tx/0xcbb6443ee8c4a566b735f8d41bf04210e330578908c1d0d7d4bf7cde2144faa5
3) 10000*(10^18) tokens approved for flex-staking contract to use stake() method
https://testnet.bscscan.com/tx/0x14ab430855e5897415e84b530495a348bb828ecd50044b85e5d5e43ed68a8d8b#eventlog
4) Staked 10*(10^18) tokens for 5 mins
https://testnet.bscscan.com/tx/0x4ef22546965c290e8f8a4c02014d952a7ab260e57544ff0d9b95cd24c1c01def
5) Returned tokens with reward 
https://testnet.bscscan.com/tx/0x63c3fb14be9c6caeb6762c228ea4c913741417a3046ac26c543a04def151f02d
